services:
  # Web Service
  - type: web
    name: debt-tracker
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn myproject.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: DJANGO_SETTINGS_MODULE
        value: myproject.settings
